### ISSUE TITLE
List API points to Get

### ISSUE THREAD

**Issue by dannio** [docusign/docusign-ruby-client#10]
I was looking at listing all the templates available in my account and noticed that it's missing, but I found:

````
# Gets a list of templates for a specified account.
    # Retrieves the definition of the specified template.
    # @param account_id The external account number (int) or account ID Guid.
    # @param template_id The ID of the template being accessed.
    # @param DocuSign_eSign::GetOptions Options for modifying the behavior of the function.
    # @return [EnvelopeTemplate]
    def get(account_id, template_id, options = DocuSign_eSign::GetOptions.default)
      data, _status_code, _headers = get_with_http_info(account_id, template_id, options)
      return data
    end
````

But the description and the actual function doesn't match.

**Comment by LarryKlugerDS** [comment]
To list the templates in an account use [Templates::list](https://developers.docusign.com/esign-rest-api/reference/Templates/Templates/list)

In the Ruby SDK, that's method Templates::ListTemplates defined in source file [api/templates_api.rb](https://github.com/docusign/docusign-ruby-client/blob/master/lib/docusign_esign/api/templates_api.rb) starting with **line 1797**. 

I agree, it looks like the comments for the methods are SNAFU.  A program generator is used to produce the SDK and it appears to have a bug regarding the comments.

**Please use stackoverflow with tag docusignapi for these types of questions. Thank you.**

**Comment by dannio** [comment]
ahh i didn't see it that far down. Got confused by the comments when I searched list! Thanks a lot!

**Comment by LarryKlugerDS** [comment]
I've filed internal bug DCM-2736 about the confusing comments.

**Comment by dannio** [comment]
Thanks!
