### ISSUE TITLE
json gem dependency is out of date.

### ISSUE THREAD

**Issue by jwsloan** [docusign/docusign-ruby-client#13]
The gemspec for this client has: 
`s.add_runtime_dependency 'json', '~> 1.8', '>= 1.8.3'`
Running the stock swagger code gen today creates:
`s.add_runtime_dependency 'json', '~> 2.1', '>= 2.1.0'`.

We have another code gen library we are trying use alongside this one, and the above discrepancy is making that impossible. 

Version 1.8.3 of the json gem is from 2015. I am not certain what the changes are from then until today. I am not finding a changelog that would tell us.

**Comment by gsnavin** [comment]
@jwsloan Yes that was intentional. Some other issue had the same issue as yours but with JWT dependency.

I am going to close this issue for now. Let us know if you have any other questions/issues using the SDK.
