### ISSUE TITLE
Client doesn't properly handle Text tabs with Date Validation

### ISSUE THREAD

**Issue by capitalist** [docusign/docusign-ruby-client#16]
Here's the tab from the template
![Screenshot_3_14_19__17_13](https://user-images.githubusercontent.com/1639/54391903-a8006d00-467c-11e9-8453-847b647b6f94.png)

And here's the parse error
![Panel](https://user-images.githubusercontent.com/1639/54391927-b64e8900-467c-11e9-9e93-3349e1ceebe8.png)

**Comment by LarryKlugerDS** [comment]
Hi @capitalist,
Thank you for the issue report.

Which SDK method were you using when the response from DocuSign couldn't be parsed?

Thank you,
Larry

**Comment by LarryKlugerDS** [comment]
I have filed internal ticket DCM-3193.

Which SDK method were you using when the response from DocuSign couldn't be parsed?

**Comment by capitalist** [comment]
Hey, sorry for being slow - I'll get you more details on the issue today.

**Comment by capitalist** [comment]
Ok, I have it boiled down to it's essence. 

The API call is simply a `.get` on an instance of the `DocuSign_eSign::TemplatesApi'

It's the template data that isn't parsed correctly, I can send you privately the template JSON that comes from the API if that helps.

**Comment by LarryKlugerDS** [comment]
Thank you!

If you have time to confirm that removing the date validation makes the problem go away, that would be helpful since it would pinpoint that the date validation is what's triggering the bug.

Regards,
Larry

**Comment by capitalist** [comment]
Confirmed:

![image](https://user-images.githubusercontent.com/1639/54691205-3780a280-4af9-11e9-8506-cc192212a535.png)

![image](https://user-images.githubusercontent.com/1639/54693238-a7445c80-4afc-11e9-9aec-856316d54b4f.png)

**Comment by LarryKlugerDS** [comment]
Many thanks for your time on the bug report.
Regards,
Larry

**Comment by capitalist** [comment]
of course - thanks for the quick response!

**Comment by LarryKlugerDS** [comment]
Good news, this issue has been fixed with the 3.0.0.rc.1 release of the SDK and [gem](https://rubygems.org/gems/docusign_esign/versions/3.0.0.rc1). The source is available as branch [ngopala/v2.1-19.2.02](https://github.com/docusign/docusign-ruby-client/tree/ngopala/v2.1-19.2.02). 

It will be released to master and the gem will be updated in the next week.

Please comment on this issue if you spot any issues with the RC (release candidate) or the forthcoming release.

Thanks,
Larry
