### ISSUE TITLE
jwt version requirement

### ISSUE THREAD

**Issue by alexmamonchik** [docusign/docusign-ruby-client#2]
Is 2.0.0 minimum required version of jwt gem? It breaks project with existing gems. For example:
``` shell
Bundler could not find compatible versions for gem "jwt":
  In Gemfile:
    docusign_esign was resolved to 0.0.1, which depends on
      jwt (>= 2.0.0, ~> 2.0)

    omniauth-slack was resolved to 2.3.0, which depends on
      omniauth-oauth2 (~> 1.4) was resolved to 1.4.0, which depends on
        oauth2 (~> 1.0) was resolved to 1.1.0, which depends on
          jwt (< 1.5.2, ~> 1.0)
```

Can you set jwt 1.5 as minimum? jwt-2.0.0 released 22 days ago and of course most of gems still require older versions of jwt.

**Comment by LupusDei** [comment]
I want to bump this - the jwt 2.0 requirement breaks a huge number of other dependencies including anything using omniauth-oauth2, twilio, and more.

Going to work off of @alexmamonchik pull request for now.

**Comment by laertiades** [comment]
bump

**Comment by mecodess** [comment]
I have similar issue. Just that our oauth is below 1.0.: 
`
  In Gemfile:
    omniauth-auth0 (~> 1.4.1) was resolved to 1.4.2, which depends on
      omniauth-oauth2 (~> 1.1) was resolved to 1.1.2, which depends on
        oauth2 (~> 0.9.3) was resolved to 0.9.3, which depends on
          jwt (~> 0.1.8)

    twilio-ruby (~> 5.10.0) was resolved to 5.10.6, which depends on
      jwt (<= 2.5, >= 1.5)
`

**Comment by LarryKlugerDS** [comment]
I have raised this issue as internal bug report DCM-2738. Please ask your DocuSign representative to add your name and business/organization information to the internal ticket. 

Thank you.

**Comment by ah-tunecore** [comment]
We also need this issue resolved in order to properly integrate.  Is there any traction on getting this merged or different supported release with the downgraded jwt version?
