### ISSUE TITLE
Connect x.509 certificates or HMAC?

### ISSUE THREAD

**Issue by rpaskin** [docusign/docusign-ruby-client#24]
I've been using this gem for integrating my app with DocuSign, thanks for the great work.

However, DocuSign has recently send a message that certificates must be upgraded soon to Connect x.509 or HMAC. See https://developers.docusign.com/esign-rest-api/guides/connect-hmac

Would you be able to tell me if these changes apply to using this gem? Do I need to update any certificates?

thanks again for supplying this gem and thanks in advance for any tips.

Best regards,
-- Ronnie

**Comment by LarryKlugerDS** [comment]
Hi @rpaskin,
The certificate update only affects you if you're using the Connect webhooks feature from DocuSign and are explicitly checking the certificate's details.

Thank you for integrating with DocuSign,
Larry

**Comment by rpaskin** [comment]
Thank you for the reply! Cheers
