### ISSUE TITLE
Create envelope with documents for certain formats failing.

### ISSUE THREAD

**Issue by vaidhyanathan-ananthakrishnan** [docusign/docusign-ruby-client#25]
I tried to create envelope using docusign_rest gem, it is failing only for certain MIME types files such as (CSV,png...), but working fine for few things like (JPEG,PDF...)

Version used :  docusign_rest (0.4.4)
````
File params:
{"file1"=>#<UploadIO:0x00007feac1ec3930 
 @content_type="text/csv",
 @original_filename="local.path",
 @local_path="local.path",
 @io=#<StringIO:0x00007feac1ed1cd8 
 @base_uri=#<URI::HTTPS https://s3.amazonaws.com/xxx_Sample_CSV%20%282%29%20%281%29.csv?AWSAccessKeyId=xxxxx&Expires=xxx&Signature=xxxxxx>,
 @meta={"x-amz-id-2"=>"xx/xxx+xxx=",
   "x-amz-request-id"=>"xx",
   "date"=>"Thu, 03 Oct 2019 13:13:19 GMT",
   "last-modified"=>"Thu, 03 Oct 2019 13:12:27 GMT",
   "etag"=>"\"xx\"",
   "x-amz-storage-class"=>"REDUCED_REDUNDANCY",
   "x-amz-server-side-encryption"=>"AES256",
   "accept-ranges"=>"bytes",
   "content-type"=>"text/csv",
   "content-length"=>"63",
   "server"=>"AmazonS3"},
 @metas={"x-amz-id-2"=>["xxx/xxx+xx="],
   "x-amz-request-id"=>["xxxx"],
   "date"=>["Thu, 03 Oct 2019 13:13:19 GMT"],
   "last-modified"=>["Thu, 03 Oct 2019 13:12:27 GMT"],
   "etag"=>["\"xx\""],
   "x-amz-storage-class"=>["REDUCED_REDUNDANCY"],
   "x-amz-server-side-encryption"=>["AES256"],
   "accept-ranges"=>["bytes"],
   "content-type"=>["text/csv"],
   "content-length"=>["63"],
   "server"=>["AmazonS3"]},
 @status=["200", "OK"]>,
 @opts={"Content-Disposition"=>"file; documentid=1"}>}
````

Getting the below Error 

{"errorCode"=>"UNABLE_TO_CONVERT_DOCUMENT", "message"=>"System was unable to convert this document to a PDF. Unable to convert Document(local.path) to a PDF. Error: UserId:xxxxxxxxxxxx IPAddress:xxx.xxx.xxxx Source:ApiRESTv2:FileType path is ineligible for conversion."}

**Comment by LarryKlugerDS** [comment]
Check that you have set the `fileExtension` attribute of the `document` object within your Envelopes::create call.

Also:

1. This type of question is best asked on stackoverflow, using the docusignapi tag
1. I recommend upgrading to the new version of the SDK gem. See https://rubygems.org/gems/docusign_esign/versions/3.0.0.rc1

**Comment by vaidhyanathan-ananthakrishnan** [comment]
Thanks. Figured out the issue, it was because of file processor causing random issues in the old version based on size. 

Closing this issue.
