### ISSUE TITLE
Authenticate multiple users with their docusign account within your application

### ISSUE THREAD

**Issue by RajOfficeTroops** [docusign/docusign-ruby-client#51]
One use case that I'm working on currently is to allow users to authenticate their docusign account within our application.
I'm following the authentication code grant.

For that to work, I'm setting few config variables in application.rb for example client_id, client_secret etc.
The callback that takes place through to `/oauth/auth` uses these values set in config in the request url for authentication.

For authentication to take place for various users, do we need to capture their client_id, client_secret in a form and then needs to be overridden in `Docusign client`?
Or am I using a wrong strategy here?

**Comment by LarryKlugerDS** [comment]
Sorry for the slow reply. 

The `client_id` and `secret` are for your app, not for a specific user.

So for a multi-tenant app, you should have one client_id, one secret, and your state for each of your users should include their:

* account_id
* base_url  
* access_token
* refresh_token
* expiration datetime for the access_token
* expiration datetime for the refresh_token (30 days from when you received it)
* user's name on the DocuSign system (optional)
* user's email on the DocuSign system (optional)
* account's name on the DocuSign system (optional)

You can use the refresh token to obtain a new access token if the access token has expired. That way you don't need to bother the user with a re-authentication request.

If you include the `extended` scope in your initial OAuth Authorization Code grant request, then everytime you use the refresh token, you will receive back a new refresh token, good for another 30 days. That way, the user will never need to re-authenticate with DocuSign as long as they use your app at least once every 30 days.
