### ISSUE TITLE
Can't find template

### ISSUE THREAD

**Issue by christoffer-wb** [docusign/docusign-ruby-client#52]
# Issue
### Can't find template on create

Following the quick examples to prototype. https://github.com/docusign/qs-ruby/blob/master/app/controllers/embedded_signing_controller.rb

Set up a sandbox, account, generated an `access_token`, entered my `account_id` from the top right, created a template with the file name specified, as a solution to why it wasn't working...`file_name = 'World_Wide_Corp_lorem.pdf' # The document to be signed.` Tried creating a folder called `data`.

<img width="317" alt="Screen Shot 2020-07-07 at 11 32 56 AM" src="https://user-images.githubusercontent.com/53314692/86826649-e544f700-c045-11ea-97ef-4a9e1220d92b.png">

Get the error below

```
No such file or directory @ rb_sysopen - data/test_pdf excluded from capture: DSN not set

Errno::ENOENT (No such file or directory @ rb_sysopen - data/test_pdf):
```

I'm stuck.

**Comment by christoffer-wb** [comment]
I guess this was specifically for the cloned project, and it doesn't work with the sandbox? Either way, think I'm past this as I've moved on to getting an auth_token from my demo account

**Comment by LarryKlugerDS** [comment]
Hi @christoffer-wb , I'm sorry you had this problem. You're right, the best example to work from is [code-examples-ruby](https://github.com/docusign/code-examples-ruby) since it includes authentication.

For general questions about the examples, GitHub with tag `docusignapi` is the best route for help.
