### ISSUE TITLE
Authenticating docusign via Rails API (Omniauth + Devise)  + JS Frontend

### ISSUE THREAD

**Issue by RajGanguly** [docusign/docusign-ruby-client#54]
I'm trying to create an authentication flow using `Auth Code Grant` where I've added necessary omniauth strategy for Docusign to create `/auth/docusign` routes in Rails API only application.  

Here are the steps followed
I'm issuing a request to the route from VueJS client.
`window.open("http://localhost:4000/auth/docusign", "targetWindow", "width=350,height=250")`

After user enters credentials and on successful login I'm calling the callback:

```
class SessionsController < Devise::SessionsController
  def docusign
    internal_destroy
    @success = false
    userinfo = request.env['omniauth.auth']
    request_info = request.env['omniauth.params'] 
    if userinfo
      info = userinfo.info
      cred = userinfo.credentials
      user = User.find_by(email: info['email']) || User.find_by(id: session[:user_id])
      if user
        organization = user.organization
        organization.organization_providers.where(provider_name: 'Docusign').destroy_all
        OrganizationProvider.create(email: info['email'], token_expires_at: Time.at(cred['expires_at']), token_expires_at: Time.now, provider_name: 'Docusign', organization_id: organization.id, token: cred.token)
        @success = true
      end 
    end 
    render 'sessions/docusign'      
  end
end
```

I'd like to pass some params (which I'm accessing in the callback as `request.env['omniauth.params']`) for executing some backend tasks in the method.
When I try `window.open("http://localhost:4000/auth/docusign?email='"+email+"'", "targetWindow", "width=350,height=250")`

It says that the url doesn't match with any redirect urls

I have also tried passing in `redirect_to('/auth/docusign',  query: query)` but on doing so, it doesn't open in a browser due to CORS.

I'm also trying to set it in session cookie, but since it's an API only server, I'm still working towards setting up `cookie store`.

**Question**
Which is the best way to achieve this? To pass some params in the callback and retrieve it.

Then the execution flow continues on the Rails server and the window serves a page with an appropriate response as per authentication status. However during this time, the client window which started the request is not aware of the authentication outcome.

**Question** 
 How can I communicate to the VueJS client that the authentication process is completed?

**Question**
Am I doing the above flow correctly or are there any better ways to achieve the same?

Thanks in advance

**Comment by LarryKlugerDS** [comment]
Re:
> Which is the best way to achieve this? To pass some params in the callback and retrieve it.

Use the state parameter of the authorization code flow. Since you should also use the state parameter with a random nounce, you can include a separator. Eg `state=<my state info>|<random nounce>`

But you'd need to modify either OmniAuth or the DocuSign strategy to support this.

Another option is to use your framework's session support or a cookie.

Re:
>How can I communicate to the VueJS client that the authentication process is completed?

Sorry, I don't know VueJS
