### ISSUE TITLE
List documents api always returning first document

### ISSUE THREAD

**Issue by RajOfficeTroops** [docusign/docusign-ruby-client#57]
I am fetching documents for a template `templates_api.list_documents(account_id, template_id)` which I plan to iterate and fetch document preview images to show by `templates_api.get_document_page_image(account_id, document_id, (page_id, template_id)`.

However I'm getting only the first document as response to `list_documents` api.
Tried it with templates with pdf files with multiple pages.

`gem 'docusign_esign', '~> 3.3.0' `

**Comment by LarryKlugerDS** [comment]
Closing...please re-open if this is still an issue. Thank you
