### ISSUE TITLE
Further sdk development question

### ISSUE THREAD

**Issue by jwsloan** [docusign/docusign-ruby-client#6]
Thank you for providing this sdk. We were just about to start writing our own when we found this. 

I had some ideas for contributing back to this repo. Is that someone you would welcome, or do you plan to simply regenerate using swagger as the api gets updated?

**Comment by Ergin008** [comment]
Hi @jwsloan, thanks for reaching out.  You are correct in that we generate this (and most our other SDKs) using Swagger so downstream changes eventually get overwritten if we merge them in.  As such we don't except them unless they are changes to non auto-generated files. 

However feel free to open issues and provide feedback/suggestions as they arise and we can consider incorporating them further upstream if it's a good change.  

Thanks for using the DocuSign API! 👍

**Comment by jwsloan** [comment]
Thank you for the quick response, @Ergin008! 

What I would love to have are methods on the models that use the corresponding api calls to either perform actions, or retrieve associated models.

Something like:
```
envelope = DocuSign_eSign::Envelope.find(envelope_id)
envelope.void if some_condition
# or
envelope.signers.map { |signer| signer.some_method }
```

In both of those cases, the model would use `DocuSign_eSign::EnvelopesApi` to make the necessary calls. 

Maybe I'll create another gem that wraps this one, and provides those features. Probably only the ones we need right now, but maybe it would be useful, and others would contribute more. Thoughts?
