### ISSUE TITLE
Bad request

### ISSUE THREAD

**Issue by bennyzr** [docusign/docusign-ruby-client#8]
Hi,

While trying to login using the sample code on the readme I am getting an error:

    ETHON: Libcurl initialized
    ETHON: performed EASY effective_url=https://account-d.docusign.com/oauth/token  response_code=400 return_code=ok total_time=0.436539
    DocuSign_eSign::ApiError: Bad Request
	from /home/dev/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/docusign_esign-1.0.0/lib/docusign_esign/api_client.rb:66:in `call_api'
	from /home/dev/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/docusign_esign-1.0.0/lib/docusign_esign/api_client.rb:410:in `configure_jwt_authorization_flow'

Any ideas why I am getting this?

Thanks,
Ben

**Comment by ajspera** [comment]
I was just running into this and my issue was I hadn't granted consent. This comes after creating all the integrator keys and RSA keypairs. Look at the granting consent section here https://developers.docusign.com/esign-rest-api/guides/authentication/oauth2-jsonwebtoken. Don't ask me why you have to do this after the same account set up the key in the first place, this entire API experience has been like pulling teeth, get ready for more errors after you get this part sorted...

**Comment by LarryKlugerDS** [comment]
Hi,
Unfortunately the error response from the SDK does not directly include the specific error from the DocuSign platform. You should look at the `response.body` to see the underlying error.

See line 54 of [api_client.rb](https://github.com/docusign/docusign-ruby-client/blob/master/lib/docusign_esign/api_client.rb)

As @ajspera says, a likely problem if you are using JWT auth and impersonating someone is that consent needs to be granted. There are two ways to do that:

Preferred: grant blanket consent for the Integration Key to impersonate anyone in an account. To do this, you use the Organization Administration tool. Your account needs to purchase Organization Administration and SSO too.

The alternative is for each account user who will be impersonated to personally grant consent. This is done (once per person) by executing the first part of the Authorization Code Grant flow.

@ajspera, I'm sorry that you had difficulty in getting going with the API and SDK. If you'd like to provide me more information, I'd be happy to speak with you on the phone or by email.  Let me know via larry dot kluger at docusign c o m

@bennyzr, I'd also be happy to speak with you about your experiences with the API and SDK.

Thanks,
Larry
