### ISSUE TITLE
DocuSign_eSign::ApiError (Bad Request)

### ISSUE THREAD

**Issue by dannio** [docusign/docusign-ruby-client#9]
I'm new to using Docusign and am trying to use this to connect to my sandbox account where I've set up the API integrator keys and generated the RSA keys and saved it on a file on my local computer (docusign.pem)

I'm following the instructions for login in the read me but I just constantly run into **DocuSign_eSign::ApiError (Bad Request)** error.

I've read online that user consent is required first, but not much else is given.

Is there a step I need to perform before? I've tried manually triggering getting an access token by doing:

````require "uri"
require "net/http"
integration_and_secret = Base64.encode64("#{integration_key};#{secret}")
uri = URI.parse("https://account-d.docusign.com/oauth/token")

http = Net::HTTP.new(uri.host, uri.port)

http.use_ssl = true
http.verify_mode = OpenSSL::SSL::VERIFY_NONE

request = Net::HTTP::Post.new(uri.request_uri)
request['Authorization'] = "Basic #{integration_and_secret}"
request.body = "grant_type=authorization_code&code=***code***"
response = http.request(request)
`````
I simply get Errno::ECONNRESET: Connection reset by peer by doing this.

Any help on this would be greatly appreciated!

**Comment by LarryKlugerDS** [comment]
Hi @dannio,

Individual user consent to allow impersonation by a JWT token request is done by following the first step in the OAuth Authorization Code Grant flow.

Do this by 

1. Open demo.docusign.net, login, and go to the Admin Tool.
2. Add `https://docusign.com` as a redirect URI to your Integration Key (client id)
3. opening a browser and visiting the following URL:

````
https://account-d.docusign.com/oauth/auth?response_type=code&scope=signature%20impersonation&client_id=CLIENT_ID&redirect_uri=https://docusign.com
````
Where CLIENT_ID is your client id.

You should see first a login screen (unless you're still logged in), then a permissions grant screen.
After granting permission, you can go back and delete the Redirect URI from your client id if you wish.

Next, retry your Ruby app.

More information on this step: https://www.docusign.com/blog/dsdev-using-the-oauth-jwt-flow/

**Comment by dannio** [comment]
sorry bit confused with the terms here. When you say client ID, do you mean the Account ID or the Integrator Key?

**Comment by LarryKlugerDS** [comment]
Sorry for not being clear.

`client id` is OAuth terminology. For DocuSign, `client id` is the exact same as `Integration Key` and `Integrators Key` (we use both terms on occasion).

**Comment by dannio** [comment]
Ah ok thanks.

I've tried what you just described just now and it doesn't seem to have worked. I'm still getting the bad request error.

I'm doing this on my local environment so wondering if that may be an issue?

**Comment by LarryKlugerDS** [comment]
Note that granting permission is a one time step per user who will be impersonated. 

And even better than asking the users to individually grant permission is to grant blanket permission at the DocuSign organization level.

**Comment by dannio** [comment]
I understand the consent levels in docusign, but I don't have organization dashboard right now as I've just started and made this sandbox account. 

Is the app meant to appear in the integrations section? I don't see anything other than the default apps offered.

**Comment by LarryKlugerDS** [comment]
What didn't work? Did you get the permissions screen from DocuSign?

**Comment by LarryKlugerDS** [comment]
Great! Can you give me the url or a more exact reference to where we have the wrong information about the `user_id` -- I'd like to fix the error.

**Comment by dannio** [comment]
https://github.com/docusign/docusign-ruby-client

it's the main readme. I got confused as it gave:

user_id = '[REQUIRED]'

and in the main admin docusign portal it says:

**API Username**
*key* or *email*

So I wasn't sure which one out of these 2, and **API Account ID** to use. 

Also, the Oauth2 request I sent off missed off ````scope=impersonation```` which I think may have been the main issue. (I was following the main Oauth2 documentation which just had ````Signature````)

**Comment by LarryKlugerDS** [comment]
Thank you! I will work to get the docs improved in those areas.

**Comment by dannio** [comment]
thanks a lot you've been a great help!

quick question while I'm here. Is there an example of how an eventNotification is set for an envelope?

is that added via the ````options````?

i.e from what I can see in the models:
````
options = DocuSign_eSign::CreateEnvelopeOptions.new
options.notification_uri = *webhook_uri*
envelopes_api = DocuSign_eSign::EnvelopesApi.new(api_client)
envelope = envelopes_api.create_envelope_with_http_info(account_id, envelop_definition, options)
````
Or is there an other way I'm meant to do this? And setting other options for webhook notifications like custom fields?

**Comment by LarryKlugerDS** [comment]
Hi, Do you have this solved? eventNotification is an item in the request object in the Envelopes::create call. It is not a query parameter.

**Comment by LarryKlugerDS** [comment]
Something like the following:

(untested code...)
````
envelope_definition = DocuSign_eSign::EnvelopeDefinition.new

event_notification = DocuSign_eSign::EventNotification.new
event_notification.url = "https://foo.example.com/listenerApp"

e1 = DocuSign_eSign.EnvelopeEvent.new
e1.envelope_event_status_code = "Sent"
e2 = DocuSign_eSign.EnvelopeEvent.new
e2.envelope_event_status_code = "Completed"

event_notification.envelope_events = [e1, e2]
envelope_definition.event_notification = event_notification

... the rest of your envelope definition
````

**Comment by dannio** [comment]
Ahh I see now. I haven't dived into the models a lot yet so I didn't notice these classes. 

Thanks, that made things a lot clearer!
